import { buildEconomy } from '../economy/factory';
import { CLASSIC_PRESET } from '../economy/presets';
import { buildBoardModel, TileBlueprint } from '../modelBuilder';

const economy = buildEconomy({
  key: 'classic-8x8',
  label: 'Classic 8x8',
  preset: CLASSIC_PRESET,
  propertyGroups: [
    { id: 'brown', label: 'Brown', color: '#8B4513', propertyCount: 2 },
    { id: 'lightblue', label: 'Light Blue', color: '#87CEEB', propertyCount: 3 },
    { id: 'purple', label: 'Purple', color: '#8B008B', propertyCount: 2 },
    { id: 'orange', label: 'Orange', color: '#FFA500', propertyCount: 3 },
    { id: 'red', label: 'Red', color: '#FF0000', propertyCount: 2 },
    { id: 'yellow', label: 'Yellow', color: '#FFFF00', propertyCount: 2 },
    { id: 'green', label: 'Green', color: '#008000', propertyCount: 2 },
    { id: 'blue', label: 'Blue', color: '#0000FF', propertyCount: 2 },
  ],
  properties: [
    { id: 'mediterranean-avenue', groupId: 'brown', price: 60 },
    { id: 'baltic-avenue', groupId: 'brown', price: 60 },
    { id: 'oriental-avenue', groupId: 'lightblue', price: 100 },
    { id: 'vermont-avenue', groupId: 'lightblue', price: 100 },
    { id: 'connecticut-avenue', groupId: 'lightblue', price: 120 },
    { id: 'st-charles-place', groupId: 'purple', price: 140 },
    { id: 'states-avenue', groupId: 'purple', price: 140 },
    { id: 'st-james-place', groupId: 'orange', price: 180 },
    { id: 'tennessee-avenue', groupId: 'orange', price: 180 },
    { id: 'new-york-avenue', groupId: 'orange', price: 200 },
    { id: 'kentucky-avenue', groupId: 'red', price: 220 },
    { id: 'indiana-avenue', groupId: 'red', price: 220 },
    { id: 'atlantic-avenue', groupId: 'yellow', price: 260 },
    { id: 'ventnor-avenue', groupId: 'yellow', price: 260 },
    { id: 'pacific-avenue', groupId: 'green', price: 300 },
    { id: 'north-carolina-avenue', groupId: 'green', price: 300 },
    { id: 'park-place', groupId: 'blue', price: 350 },
    { id: 'boardwalk', groupId: 'blue', price: 400 },
  ],
});

const layout: TileBlueprint[] = [
  { type: 'GO' },
  { type: 'PROPERTY', propertyId: 'mediterranean-avenue' },
  { type: 'COMMUNITY_CHEST' },
  { type: 'PROPERTY', propertyId: 'baltic-avenue' },
  { type: 'TAX', amount: 200, name: 'Income Tax' },
  { type: 'RAILROAD', name: 'Reading Railroad' },
  { type: 'PROPERTY', propertyId: 'oriental-avenue' },
  { type: 'PROPERTY', propertyId: 'vermont-avenue' },
  { type: 'JAIL' },
  { type: 'PROPERTY', propertyId: 'connecticut-avenue' },
  { type: 'PROPERTY', propertyId: 'st-charles-place' },
  { type: 'PROPERTY', propertyId: 'states-avenue' },
  { type: 'PROPERTY', propertyId: 'st-james-place' },
  { type: 'PROPERTY', propertyId: 'tennessee-avenue' },
  { type: 'PROPERTY', propertyId: 'new-york-avenue' },
  { type: 'UTILITY', name: 'Electric Company' },
  { type: 'FREE_PARKING' },
  { type: 'PROPERTY', propertyId: 'kentucky-avenue' },
  { type: 'CHANCE' },
  { type: 'PROPERTY', propertyId: 'indiana-avenue' },
  { type: 'PROPERTY', propertyId: 'atlantic-avenue' },
  { type: 'TAX', amount: 75, name: 'Luxury Tax' },
  { type: 'PROPERTY', propertyId: 'ventnor-avenue' },
  { type: 'GO_TO_JAIL' },
  { type: 'PROPERTY', propertyId: 'pacific-avenue' },
  { type: 'CHANCE' },
  { type: 'PROPERTY', propertyId: 'north-carolina-avenue' },
  { type: 'RAILROAD', name: 'Short Line' },
  { type: 'PROPERTY', propertyId: 'park-place' },
  { type: 'UTILITY', name: 'Water Works' },
  { type: 'PROPERTY', propertyId: 'boardwalk' },
  { type: 'COMMUNITY_CHEST' },
];

export const CLASSIC_8x8 = buildBoardModel({
  key: 'classic-8x8',
  label: 'Classic 8x8',
  sideLength: 8,
  economy,
  layout,
});
