import { buildEconomy } from '../economy/factory';
import { EXTENDED_PRESET } from '../economy/presets';
import { buildBoardModel, TileBlueprint } from '../modelBuilder';

const economy = buildEconomy({
  key: 'extended-12x12',
  label: 'Extended 12x12',
  preset: EXTENDED_PRESET,
  propertyGroups: [
    { id: 'brown', label: 'Brown', color: '#8B4513', propertyCount: 3 },
    { id: 'lightblue', label: 'Light Blue', color: '#87CEEB', propertyCount: 3 },
    { id: 'purple', label: 'Purple', color: '#8B008B', propertyCount: 3 },
    { id: 'orange', label: 'Orange', color: '#FFA500', propertyCount: 3 },
    { id: 'pink', label: 'Pink', color: '#FFC0CB', propertyCount: 3 },
    { id: 'red', label: 'Red', color: '#FF0000', propertyCount: 3 },
    { id: 'yellow', label: 'Yellow', color: '#FFFF00', propertyCount: 3 },
    { id: 'green', label: 'Green', color: '#008000', propertyCount: 3 },
    { id: 'blue', label: 'Blue', color: '#0000FF', propertyCount: 3 },
    { id: 'cyan', label: 'Cyan', color: '#00FFFF', propertyCount: 3 },
  ],
  properties: [
    { id: 'mediterranean-avenue', groupId: 'brown', price: 80 },
    { id: 'baltic-avenue', groupId: 'brown', price: 80 },
    { id: 'vine-street', groupId: 'brown', price: 100 },
    { id: 'oriental-avenue', groupId: 'lightblue', price: 120 },
    { id: 'vermont-avenue', groupId: 'lightblue', price: 120 },
    { id: 'connecticut-avenue', groupId: 'lightblue', price: 140 },
    { id: 'st-charles-place', groupId: 'purple', price: 180 },
    { id: 'states-avenue', groupId: 'purple', price: 180 },
    { id: 'virginia-avenue', groupId: 'purple', price: 200 },
    { id: 'st-james-place', groupId: 'orange', price: 220 },
    { id: 'tennessee-avenue', groupId: 'orange', price: 220 },
    { id: 'new-york-avenue', groupId: 'orange', price: 240 },
    { id: 'wall-street', groupId: 'pink', price: 280 },
    { id: 'fifth-avenue', groupId: 'pink', price: 280 },
    { id: 'broadway', groupId: 'pink', price: 300 },
    { id: 'kentucky-avenue', groupId: 'red', price: 280 },
    { id: 'indiana-avenue', groupId: 'red', price: 280 },
    { id: 'illinois-avenue', groupId: 'red', price: 300 },
    { id: 'atlantic-avenue', groupId: 'yellow', price: 320 },
    { id: 'ventnor-avenue', groupId: 'yellow', price: 320 },
    { id: 'marvin-gardens', groupId: 'yellow', price: 340 },
    { id: 'pacific-avenue', groupId: 'green', price: 360 },
    { id: 'north-carolina-avenue', groupId: 'green', price: 360 },
    { id: 'pennsylvania-avenue', groupId: 'green', price: 380 },
    { id: 'park-place', groupId: 'blue', price: 400 },
    { id: 'boardwalk', groupId: 'blue', price: 420 },
    { id: 'mayfair', groupId: 'blue', price: 440 },
    { id: 'sunset-boulevard', groupId: 'cyan', price: 360 },
    { id: 'rodeo-drive', groupId: 'cyan', price: 360 },
    { id: 'hollywood-boulevard', groupId: 'cyan', price: 380 },
  ],
});

const layout: TileBlueprint[] = [
  { type: 'GO' },
  { type: 'PROPERTY', propertyId: 'mediterranean-avenue' },
  { type: 'COMMUNITY_CHEST' },
  { type: 'PROPERTY', propertyId: 'baltic-avenue' },
  { type: 'PROPERTY', propertyId: 'vine-street' },
  { type: 'TAX', amount: 200, name: 'Income Tax' },
  { type: 'PROPERTY', propertyId: 'oriental-avenue' },
  { type: 'PROPERTY', propertyId: 'vermont-avenue' },
  { type: 'CHANCE' },
  { type: 'PROPERTY', propertyId: 'connecticut-avenue' },
  { type: 'UTILITY', name: 'Electric Company' },
  { type: 'PROPERTY', propertyId: 'st-charles-place' },
  { type: 'JAIL' },
  { type: 'PROPERTY', propertyId: 'states-avenue' },
  { type: 'PROPERTY', propertyId: 'virginia-avenue' },
  { type: 'COMMUNITY_CHEST' },
  { type: 'PROPERTY', propertyId: 'st-james-place' },
  { type: 'PROPERTY', propertyId: 'tennessee-avenue' },
  { type: 'CHANCE' },
  { type: 'PROPERTY', propertyId: 'new-york-avenue' },
  { type: 'RAILROAD', name: "Pennsylvania Railroad" },
  { type: 'PROPERTY', propertyId: 'wall-street' },
  { type: 'PROPERTY', propertyId: 'fifth-avenue' },
  { type: 'PROPERTY', propertyId: 'broadway' },
  { type: 'FREE_PARKING' },
  { type: 'PROPERTY', propertyId: 'kentucky-avenue' },
  { type: 'TAX', amount: 150, name: 'Luxury Tax' },
  { type: 'PROPERTY', propertyId: 'indiana-avenue' },
  { type: 'PROPERTY', propertyId: 'illinois-avenue' },
  { type: 'COMMUNITY_CHEST' },
  { type: 'PROPERTY', propertyId: 'atlantic-avenue' },
  { type: 'PROPERTY', propertyId: 'ventnor-avenue' },
  { type: 'UTILITY', name: 'Water Works' },
  { type: 'PROPERTY', propertyId: 'marvin-gardens' },
  { type: 'CHANCE' },
  { type: 'PROPERTY', propertyId: 'pacific-avenue' },
  { type: 'GO_TO_JAIL' },
  { type: 'PROPERTY', propertyId: 'north-carolina-avenue' },
  { type: 'PROPERTY', propertyId: 'pennsylvania-avenue' },
  { type: 'PROPERTY', propertyId: 'park-place' },
  { type: 'RAILROAD', name: 'Short Line' },
  { type: 'PROPERTY', propertyId: 'boardwalk' },
  { type: 'PROPERTY', propertyId: 'mayfair' },
  { type: 'COMMUNITY_CHEST' },
  { type: 'PROPERTY', propertyId: 'sunset-boulevard' },
  { type: 'PROPERTY', propertyId: 'rodeo-drive' },
  { type: 'PROPERTY', propertyId: 'hollywood-boulevard' },
  { type: 'CHANCE' },
];

export const EXTENDED_12x12 = buildBoardModel({
  key: 'extended-12x12',
  label: 'Extended 12x12',
  sideLength: 12,
  economy,
  layout,
});
