import { buildEconomy } from '../economy/factory';
import { MEGA_PRESET } from '../economy/presets';
import { buildBoardModel, TileBlueprint } from '../modelBuilder';

const economy = buildEconomy({
  key: 'mega-16x16',
  label: 'Mega 16x16',
  preset: MEGA_PRESET,
  propertyGroups: [
    { id: 'brown', label: 'Brown', color: '#8B4513', propertyCount: 3 },
    { id: 'lightblue', label: 'Light Blue', color: '#87CEEB', propertyCount: 3 },
    { id: 'purple', label: 'Purple', color: '#8B008B', propertyCount: 4 },
    { id: 'orange', label: 'Orange', color: '#FFA500', propertyCount: 4 },
    { id: 'red', label: 'Red', color: '#FF0000', propertyCount: 4 },
    { id: 'yellow', label: 'Yellow', color: '#FFFF00', propertyCount: 4 },
    { id: 'green', label: 'Green', color: '#008000', propertyCount: 4 },
    { id: 'blue', label: 'Blue', color: '#0000FF', propertyCount: 4 },
    { id: 'pink', label: 'Pink', color: '#FFC0CB', propertyCount: 4 },
    { id: 'cyan', label: 'Cyan', color: '#00FFFF', propertyCount: 4 },
    { id: 'gold', label: 'Gold', color: '#FFD700', propertyCount: 4 },
    { id: 'silver', label: 'Silver', color: '#C0C0C0', propertyCount: 4 },
  ],
  properties: [
    { id: 'old-kent-road', groupId: 'brown', price: 100 },
    { id: 'whitechapel-road', groupId: 'brown', price: 110 },
    { id: 'lambeth-road', groupId: 'brown', price: 120 },
    { id: 'the-angel-islington', groupId: 'lightblue', price: 140 },
    { id: 'euston-road', groupId: 'lightblue', price: 140 },
    { id: 'pentonville-road', groupId: 'lightblue', price: 160 },
    { id: 'pall-mall', groupId: 'purple', price: 180 },
    { id: 'whitehall', groupId: 'purple', price: 190 },
    { id: 'northumberland-avenue', groupId: 'purple', price: 200 },
    { id: 'bow-street', groupId: 'purple', price: 210 },
    { id: 'marlborough-street', groupId: 'orange', price: 220 },
    { id: 'vine-street', groupId: 'orange', price: 220 },
    { id: 'strand', groupId: 'orange', price: 230 },
    { id: 'fleet-street', groupId: 'orange', price: 240 },
    { id: 'trafalgar-square', groupId: 'red', price: 260 },
    { id: 'leicester-square', groupId: 'red', price: 260 },
    { id: 'coventry-street', groupId: 'red', price: 270 },
    { id: 'piccadilly', groupId: 'red', price: 280 },
    { id: 'regent-street', groupId: 'yellow', price: 300 },
    { id: 'oxford-street', groupId: 'yellow', price: 300 },
    { id: 'bond-street', groupId: 'yellow', price: 310 },
    { id: 'park-lane', groupId: 'yellow', price: 320 },
    { id: 'mayfair', groupId: 'green', price: 340 },
    { id: 'kensington-high-street', groupId: 'green', price: 340 },
    { id: 'notting-hill', groupId: 'green', price: 350 },
    { id: 'camden-town', groupId: 'green', price: 360 },
    { id: 'greenwich', groupId: 'blue', price: 360 },
    { id: 'chelsea', groupId: 'blue', price: 370 },
    { id: 'hyde-park', groupId: 'blue', price: 370 },
    { id: 'kensal-rise', groupId: 'blue', price: 380 },
    { id: 'abbey-road', groupId: 'pink', price: 380 },
    { id: 'primrose-hill', groupId: 'pink', price: 380 },
    { id: 'richmond', groupId: 'pink', price: 390 },
    { id: 'hampstead', groupId: 'pink', price: 400 },
    { id: 'dulwich', groupId: 'cyan', price: 400 },
    { id: 'wimbledon', groupId: 'cyan', price: 410 },
    { id: 'twickenham', groupId: 'cyan', price: 410 },
    { id: 'st-johns-wood', groupId: 'cyan', price: 420 },
    { id: 'belgravia', groupId: 'gold', price: 420 },
    { id: 'knightsbridge', groupId: 'gold', price: 430 },
    { id: 'victoria', groupId: 'gold', price: 430 },
    { id: 'westminster', groupId: 'gold', price: 440 },
    { id: 'city-of-london', groupId: 'silver', price: 440 },
    { id: 'canary-wharf', groupId: 'silver', price: 450 },
    { id: 'docklands', groupId: 'silver', price: 450 },
    { id: 'stratford', groupId: 'silver', price: 460 },
  ],
});

const layout: TileBlueprint[] = [
  { type: 'GO' },
  { type: 'PROPERTY', propertyId: 'old-kent-road' },
  { type: 'COMMUNITY_CHEST' },
  { type: 'PROPERTY', propertyId: 'whitechapel-road' },
  { type: 'PROPERTY', propertyId: 'lambeth-road' },
  { type: 'TAX', amount: 250, name: 'Income Tax' },
  { type: 'PROPERTY', propertyId: 'the-angel-islington' },
  { type: 'PROPERTY', propertyId: 'euston-road' },
  { type: 'CHANCE' },
  { type: 'PROPERTY', propertyId: 'pentonville-road' },
  { type: 'PROPERTY', propertyId: 'pall-mall' },
  { type: 'UTILITY', name: 'Electric Company' },
  { type: 'PROPERTY', propertyId: 'whitehall' },
  { type: 'PROPERTY', propertyId: 'northumberland-avenue' },
  { type: 'PROPERTY', propertyId: 'bow-street' },
  { type: 'PROPERTY', propertyId: 'marlborough-street' },
  { type: 'JAIL' },
  { type: 'PROPERTY', propertyId: 'vine-street' },
  { type: 'PROPERTY', propertyId: 'strand' },
  { type: 'COMMUNITY_CHEST' },
  { type: 'PROPERTY', propertyId: 'fleet-street' },
  { type: 'PROPERTY', propertyId: 'trafalgar-square' },
  { type: 'CHANCE' },
  { type: 'PROPERTY', propertyId: 'leicester-square' },
  { type: 'PROPERTY', propertyId: 'coventry-street' },
  { type: 'UTILITY', name: 'Water Works' },
  { type: 'PROPERTY', propertyId: 'piccadilly' },
  { type: 'RAILROAD', name: "King's Cross Station" },
  { type: 'PROPERTY', propertyId: 'regent-street' },
  { type: 'PROPERTY', propertyId: 'oxford-street' },
  { type: 'PROPERTY', propertyId: 'bond-street' },
  { type: 'TAX', amount: 150, name: 'Luxury Tax' },
  { type: 'FREE_PARKING' },
  { type: 'PROPERTY', propertyId: 'park-lane' },
  { type: 'PROPERTY', propertyId: 'mayfair' },
  { type: 'PROPERTY', propertyId: 'kensington-high-street' },
  { type: 'CHANCE' },
  { type: 'PROPERTY', propertyId: 'notting-hill' },
  { type: 'PROPERTY', propertyId: 'camden-town' },
  { type: 'COMMUNITY_CHEST' },
  { type: 'PROPERTY', propertyId: 'greenwich' },
  { type: 'PROPERTY', propertyId: 'chelsea' },
  { type: 'PROPERTY', propertyId: 'hyde-park' },
  { type: 'PROPERTY', propertyId: 'kensal-rise' },
  { type: 'RAILROAD', name: 'Fenchurch Street Station' },
  { type: 'PROPERTY', propertyId: 'abbey-road' },
  { type: 'PROPERTY', propertyId: 'primrose-hill' },
  { type: 'PROPERTY', propertyId: 'richmond' },
  { type: 'GO_TO_JAIL' },
  { type: 'PROPERTY', propertyId: 'hampstead' },
  { type: 'CHANCE' },
  { type: 'PROPERTY', propertyId: 'dulwich' },
  { type: 'PROPERTY', propertyId: 'wimbledon' },
  { type: 'COMMUNITY_CHEST' },
  { type: 'PROPERTY', propertyId: 'twickenham' },
  { type: 'PROPERTY', propertyId: 'st-johns-wood' },
  { type: 'PROPERTY', propertyId: 'belgravia' },
  { type: 'PROPERTY', propertyId: 'knightsbridge' },
  { type: 'PROPERTY', propertyId: 'victoria' },
  { type: 'PROPERTY', propertyId: 'westminster' },
  { type: 'PROPERTY', propertyId: 'city-of-london' },
  { type: 'PROPERTY', propertyId: 'canary-wharf' },
  { type: 'PROPERTY', propertyId: 'docklands' },
  { type: 'PROPERTY', propertyId: 'stratford' },
];

export const MEGA_16x16 = buildBoardModel({
  key: 'mega-16x16',
  label: 'Mega 16x16',
  sideLength: 16,
  economy,
  layout,
});
